services:
    mqtt-broker:
        container_name: mqtt-broker
        image: eclipse-mosquitto:2.0.15
        profiles: [dev, prod]
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./modules/mqtt-broker/config:/mosquitto/config
            - ./modules/mqtt-broker/data:/mosquitto/data
            - ./modules/mqtt-broker/log:/mosquitto/log
        restart: unless-stopped
        networks:
            - pong-network
    mqtt-explorer:
        container_name: mqtt-explorer
        image: smeagolworms4/mqtt-explorer
        profiles: [dev]
        ports:
            - 4000:4000
        volumes:
            - ./development-tools/mqtt-explorer/config:/mqtt-explorer/config
        restart: unless-stopped
        networks:
            - pong-network
    ai-paddle-control:
        container_name: ai-paddle-control
        image: ghcr.io/aaron97neu/ai-paddle-control:${TAG:-next}
        build:
            context: ./modules/ai-paddle-control
            additional_contexts:
                util: ./modules/shared
                validation: ./modules/shared/validation
                certs: ./certs
        profiles: [prod, top-player-ai-gpu]
        restart: unless-stopped
        networks:
            - pong-network
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
    ai-paddle-control-no-gpu:
        container_name: ai-paddle-control
        image: ghcr.io/aaron97neu/ai-paddle-control:${TAG:-next}
        build:
            context: ./modules/ai-paddle-control
            additional_contexts:
                util: ./modules/shared
                validation: ./modules/shared/validation
                certs: ./certs
            args:
                GPU: ""
        profiles: [top-player-ai-cpu]
        restart: unless-stopped
        networks:
            - pong-network
    human-paddle-control:
        container_name: human-paddle-control
        image: ghcr.io/aaron97neu/human-paddle-control:${TAG:-next}
        build:
            context: ./modules/human-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
        profiles: [prod, bottom-player-depth]
        volumes:
            - /dev:/dev
        device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
        #       devices:
        #        - "/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/input/input22:/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/input/input22"
        restart: unless-stopped
        networks:
            - pong-network
    tyler:
        container_name: tyler
        image: ghcr.io/aaron97neu/tyler:${TAG:-next}
        build:
            context: ./modules/tyler
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
        profiles: [dev, prod]
        ports:
            - 5003:80
        depends_on:
            - mqtt-broker
        restart: unless-stopped
        networks:
            - pong-network
        environment:
            - CHOKIDAR_USEPOLLING=true
    human-visualizer:
        container_name: human-visualizer
        image: ghcr.io/aaron97neu/human-visualizer:${TAG:-next}
        build:
            context: ./modules/human-visualizer
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
        profiles: [dev, prod]
        ports:
            - 5001:8000
        #       environment:
        #           - DEBUG=0 # Not used right now
        restart: unless-stopped
        networks:
            - pong-network
    neural-net-visualizer:
        container_name: neural-net-visualizer
        image: ghcr.io/aaron97neu/neural-net-visualizer:${TAG:-next}
        build:
            context: ./modules/neural-net-visualizer
            additional_contexts:
                util: ./modules/shared
                models: ./modules/shared/models
                certs: ./certs
        profiles: [dev, prod]
        ports:
            - 5002:8000
        restart: unless-stopped
        networks:
            - pong-network
    gameboard:
        container_name: gameboard
        image: ghcr.io/aaron97neu/gameboard:${TAG:-next}
        build:
            context: ./modules/gameboard
            additional_contexts:
                certs: ./certs
                util: ./modules/shared
        profiles: [dev, prod]
        ports:
            - 5000:80
        restart: unless-stopped
        networks:
            - pong-network
    top-web-paddle-control:
        container_name: top-web-paddle-control
        image: ghcr.io/aaron97neu/top-web-paddle-control:${TAG:-next}
        build:
            context: ./modules/web-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
            args:
                REACT_APP_PADDLE_ID: top
                REACT_APP_INCREMENT: 0.02
                REACT_APP_INTERVAL: 70
        profiles: [top-player-web]
        ports:
            - 5004:80
        restart: unless-stopped
        networks:
            - pong-network
    bottom-web-paddle-control:
        container_name: bottom-web-paddle-control
        image: ghcr.io/aaron97neu/bottom-web-paddle-control:${TAG:-next}
        build:
            context: ./modules/web-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
            args:
                REACT_APP_PADDLE_ID: bottom
                REACT_APP_INCREMENT: 0.02
                REACT_APP_INTERVAL: 70
        ports:
            - 5005:80
        profiles: [bottom-player-web]
        restart: unless-stopped
        networks:
            - pong-network

    # Keyboard control: Deprecated
    keyboard-paddle-control-bottom:
        container_name: keyboard-paddle-control
        image: keyboard-paddle-control:latest
        build:
            dockerfile: Dockerfile.zscaler
            context: ./modules/keyboard-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
        profiles: [bottom-player-keyboard]
        volumes:
            - /dev:/dev
        environment:
            - PADDLE_ID=bottom_paddle
        restart: unless-stopped
        networks:
            - pong-network

    # Keyboard control: Deprecated
    keyboard-paddle-control-top:
        container_name: keyboard-paddle-control
        image: keyboard-paddle-control:latest
        build:
            dockerfile: Dockerfile.zscaler
            context: ./modules/keyboard-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
        profiles: [top-player-keyboard]
        volumes:
            - /dev:/dev
        environment:
            - PADDLE_ID=top_paddle
        restart: unless-stopped
        networks:
            - pong-network
    single-screen-development:
        container_name: single-screen-development
        image: ghcr.io/aaron97neu/single-screen-development:${TAG:-next}
        build:
            context: ./modules/single-screen-development
            additional_contexts:
                certs: ./certs
        profiles: [dev]
        ports:
            - 5005:80
        restart: unless-stopped
        networks:
            - pong-network
    log-server:
        container_name: log-server
        image: ghcr.io/aaron97neu/log-server:${TAG:-next}
        build:
            context: ./modules/log-server
        profiles: [dev]
        environment:
            - MQTT_BROKER_URL=ws://mqtt-broker:9001
        depends_on:
            - mqtt-broker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - pong-network
networks:
    pong-network:
        name: pong-network
        driver: bridge
