# Currently this file is just the normal `docker-compose.yml`
# file with additional services which would be better done
# by just having the extra services and an extends keyword. However,
# the future plan is to replace the human paddle control mechanisms
# with a keyboard control to facilite testing without the depth
# camera, which would involve removing services. 

services:
    mqtt-broker:
        container_name: mqtt-broker
        image: eclipse-mosquitto:2.0.15
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./src/mqtt-broker/config:/mosquitto/config
            - ./src/mqtt-broker/data:/mosquitto/data
            - ./src/mqtt-broker/log:/mosquitto/log
        restart: unless-stopped
        networks:
            - pong-network
    mqtt-explorer:
        container_name: mqtt-explorer
        image: smeagolworms4/mqtt-explorer
        ports:
            - 4000:4000
        volumes:
            - ./development-tools/mqtt-explorer/config:/mqtt-explorer/config
        restart: unless-stopped
        networks:
            - pong-network
    ai-paddle-control:
        container_name: ai-paddle-control
        image: ai-paddle-control:latest
        build: 
          context: ./src/ai-paddle-control
          additional_contexts:
            util: ./src/shared/code
            validation: ./src/shared/validation
        restart: unless-stopped
        networks:
            - pong-network       
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    game-engine:
        container_name: game-engine
        image: game-engine:latest
        build: 
          context: ./src/game-engine
          additional_contexts:
            util: ./src/shared/code
        restart: unless-stopped
        networks:
            - pong-network       
    human-paddle-control:
        container_name: human-paddle-control
        image: human-paddle-control:latest
        build: 
          context: ./src/human-paddle-control
          additional_contexts:
            util: ./src/shared/code
        volumes:
            - /dev:/dev
        device_cgroup_rules:
            - 'c 81:* rmw'
            - 'c 189:* rmw'               
#       devices:
#        - "/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/input/input22:/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/input/input22"
        restart: unless-stopped
        networks:
            - pong-network       
    human-visualizer:
        container_name: human-visualizer
        image: human-visualizer:latest
        build: 
          context: ./src/human-visualizer
          additional_contexts:
            util: ./src/shared/code
        ports:
            - 5001:8000        
        restart: unless-stopped
#       environment:
#           - DEBUG=1 # No used right now
        networks:
            - pong-network       
    neural-net-visualizer:
        container_name: neural-net-visualizer
        image: neural-net-visualizer:latest
        build: 
          context: ./src/neural-net-visualizer
          additional_contexts:
            util: ./src/shared/code
            models: ./src/shared/models
        ports:
            - 5002:8000        
        restart: unless-stopped
        networks:
            - pong-network       
    clocktower-visualizer:
        container_name: clocktower-visualizer
        image: clocktower-visualizer:latest
        build:
          context: ./src/clocktower-visualizer
          additional_contexts:
            models: ./src/shared/models
        ports:
            - 5003:80        
        restart: unless-stopped
        networks:
            - pong-network       
    gameboard:
        container_name: gameboard
        image: gameboard:latest
        build: ./src/gameboard
        ports:
            - 5000:80        
        restart: unless-stopped
        networks:
            - pong-network
    audio-engine:
        container_name: audio-engine
        image: audio-engine:latest
        build: 
          context: ./src/audio-engine
        devices:
           - "/dev/snd"
        restart: unless-stopped
        networks:
            - pong-network
    web-paddle-control:
        container_name: web-paddle-control
        image: web-paddle-control:latest
        build: ./src/web-paddle-control
        environment:
        - REACT_APP_MQTT_BROKER=mqtt-broker        
        ports:
            - 5004:80
        restart: unless-stopped
        networks:
            - pong-network
        depends_on:
        - mqtt-broker                                      
networks:
    pong-network:
        name: pong-network
        driver: bridge
