# Currently this file is just the normal `docker-compose.yml`
# file with additional services which would be better done
# by just having the extra services and an extends keyword. However,
# the future plan is to replace the human paddle control mechanisms
# with a keyboard control to facilite testing without the depth
# camera, which would involve removing services.

services:
    mqtt-broker:
        container_name: mqtt-broker
        image: eclipse-mosquitto:2.0.15
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./modules/mqtt-broker/config:/mosquitto/config
            - ./modules/mqtt-broker/data:/mosquitto/data
            - ./modules/mqtt-broker/log:/mosquitto/log
        restart: unless-stopped
        networks:
            - pong-network
    mqtt-explorer:
        container_name: mqtt-explorer
        image: smeagolworms4/mqtt-explorer
        ports:
            - 4000:4000
        volumes:
            - ./development-tools/mqtt-explorer/config:/mqtt-explorer/config
        restart: unless-stopped
        networks:
            - pong-network

    # ai-paddle-control:
    #     container_name: ai-paddle-control
    #     image: ai-paddle-control:latest
    #     # image: ai-paddle-control:latest
    #     build:
    #         context: ./modules/ai-paddle-control
    #         additional_contexts:
    #             util: ./modules/shared
    #             validation: ./modules/shared/validation
    #             certs: ./certs
    #     profiles: [prod]
    #     restart: unless-stopped
    #     networks:
    #         - pong-network
    #     deploy:
    #         resources:
    #             reservations:
    #                 devices:
    #                     - driver: nvidia
    #                       count: 1
    #                       capabilities: [gpu]
    ai-paddle-control-no-gpu:
        container_name: ai-paddle-control
        build:
            context: ./modules/ai-paddle-control
            additional_contexts:
                util: ./modules/shared
                validation: ./modules/shared/validation
                certs: ./certs
        profiles: [dev]
        restart: unless-stopped
        networks:
            - pong-network
        volumes:
            - ./screens:/app/screens
            - ./files:/app/files

    # ai-paddle-control:
    #     container_name: ai-paddle-control
    #     image: ai-paddle-control:latest
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/ai-paddle-control
    #         additional_contexts:
    #             util: ./modules/shared
    #             validation: ./modules/shared/validation
    #             certs: ./certs
    #     restart: unless-stopped
    #     networks:
    #         - pong-network
    #     # deploy:
    #     #     resources:
    #     #         reservations:
    #     #             devices:
    #     #                 - driver: nvidia
    #     #                   count: 1
    #     #                   capabilities: [gpu]

    # game-engine:
    #     container_name: game-engine
    #     image: game-engine:latest
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/game-engine
    #         additional_contexts:
    #             util: ./modules/shared
    #             certs: ./certs
    #     restart: unless-stopped
    #     networks:
    #         - pong-network

    # human-paddle-control:
    #     container_name: human-paddle-control
    #     image: human-paddle-control:latest
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/human-paddle-control
    #         additional_contexts:
    #             util: ./modules/shared/code
    #             certs: ./certs
    #     volumes:
    #         - /dev:/dev
    #     device_cgroup_rules:
    #         - "c 81:* rmw"
    #         - "c 189:* rmw"
    #     #       devices:
    #     #        - "/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/input/input22:/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/input/input22"
    #     restart: unless-stopped
    #     networks:
    #         - pong-network

    # human-visualizer:
    #     container_name: human-visualizer
    #     image: human-visualizer:latest
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/human-visualizer
    #         additional_contexts:
    #             util: ./modules/shared/code
    #             certs: ./certs
    #     ports:
    #         - 5001:8000
    #     restart: unless-stopped
    #     #       environment:
    #     #           - DEBUG=1 # No used right now
    #     networks:
    #         - pong-network

    # neural-net-visualizer:
    #     container_name: neural-net-visualizer
    #     image: neural-net-visualizer:latest
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/neural-net-visualizer
    #         additional_contexts:
    #             util: ./modules/shared/code
    #             models: ./modules/shared/models
    #             certs: ./certs
    #     ports:
    #         - 5002:8000
    #     restart: unless-stopped
    #     networks:
    #         - pong-network

    # clocktower-visualizer:
    #     container_name: clocktower-visualizer
    #     image: clocktower-visualizer:latest
    #     build:
    #         context: ./modules/clocktower-visualizer
    #         additional_contexts:
    #             models: ./modules/shared/models
    #     ports:
    #         - 5003:80
    #     restart: unless-stopped
    #     networks:
    #         - pong-network

    # gameboard:
    #     container_name: gameboard
    #     image: gameboard:latest
    #     build:
    #         # dockerfile: Dockerfile.zscaler
    #         context: ./modules/gameboard
    #         additional_contexts:
    #             util: ./modules/shared
    #             certs: ./certs
    #     ports:
    #         - 5000:80
    #     depends_on:
    #         - mqtt-broker         
    #     restart: unless-stopped
    #     networks:
    #         - pong-network
    #     # volumes:
    #     # - .:/app
    #     # - /app/node_modules
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true            

    # gameboard:
    #     container_name: gameboard
    #     image: gameboard:latest
    #     build:
    #         context: ./modules/gameboard
    #         additional_contexts:
    #             util: ./modules/shared
    #             certs: ./certs
    #     profiles: [dev, prod]
    #     ports:
    #         - 5000:80
    #     restart: unless-stopped
    #     networks:
    #         - pong-network

    # audio-engine:
    #     container_name: audio-engine
    #     image: audio-engine:latest
    #     volumes:
    #         - ./tts:/app/tts
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/audio-engine
    #         additional_contexts:
    #             util: ./modules/shared
    #             certs: ./certs
    #     devices:
    #         - "/dev/snd"
    #     restart: unless-stopped
    #     networks:
    #         - pong-network

    top-web-paddle-control:
        container_name: top-web-paddle-control
        image: top-web-paddle-control:latest
        build:
            # dockerfile: Dockerfile.zscaler
            context: ./modules/web-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
            args:
                REACT_APP_PADDLE_ID: top
                REACT_APP_INCREMENT: 0.02
                REACT_APP_INTERVAL: 70
        ports:
            - 5004:80                
        restart: unless-stopped
        networks:
            - pong-network

    bottom-web-paddle-control:
        container_name: bottom-web-paddle-control
        image: bottom-web-paddle-control:latest
        build:
            # dockerfile: Dockerfile.zscaler
            context: ./modules/web-paddle-control
            additional_contexts:
                util: ./modules/shared
                certs: ./certs
            args:
                REACT_APP_PADDLE_ID: bottom
                REACT_APP_INCREMENT: 0.02
                REACT_APP_INTERVAL: 70
        ports:
            - 5005:80                
        restart: unless-stopped
        networks:
            - pong-network  

    # keyboard-paddle-control:
    #     container_name: keyboard-paddle-control
    #     image: keyboard-paddle-control:latest
    #     build:
    #         dockerfile: Dockerfile.zscaler
    #         context: ./modules/keyboard-paddle-control
    #         additional_contexts:
    #             util: ./modules/shared
    #             certs: ./certs
    #     volumes:
    #         - /dev:/dev
    #     environment:
    #         - PADDLE_ID=bottom_paddle  
    #     restart: unless-stopped
    #     networks:
    #         - pong-network    

networks:
    pong-network:
        name: pong-network
        driver: bridge
