[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dw"
version = "0.1.0"
description = "A sample Python package"

# [tool.setuptools]
# packages = [
#     "dw",
#     "dw.state_machine",
#     "dw.utils"
# ]