version: '3.8'

services:
    mqtt-broker:
        container_name: mqtt-broker
        image: eclipse-mosquitto:2.0.15
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log

