# Currently this file is just the normal `docker-compose.yml`
# file with additional services which would be better done
# by just having the extra services and an extends keyword. However,
# the future plan is to replace the human paddle control mechanisms
# with a keyboard control to facilite testing without the depth
# camera, which would involve removing services.

services:
    mqtt-broker:
        container_name: mqtt-broker
        image: eclipse-mosquitto:2.0.15
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./src/mqtt-broker/config:/mosquitto/config
            - ./src/mqtt-broker/data:/mosquitto/data
            - ./src/mqtt-broker/log:/mosquitto/log
        restart: unless-stopped
        networks:
            - pong-network
    mqtt-explorer:
        container_name: mqtt-explorer
        image: smeagolworms4/mqtt-explorer
        ports:
            - 4000:4000
        volumes:
            - ./development-tools/mqtt-explorer/config:/mqtt-explorer/config
        restart: unless-stopped
        networks:
            - pong-network
    game-engine:
        container_name: game-engine
        image: game-engine:latest
        build:
            dockerfile: Dockerfile.zscaler
            context: ./src/game-engine
            additional_contexts:
                util: ./src/shared/code
                certs: ./certs
        restart: unless-stopped
        networks:
            - pong-network
    integration-test:
        container_name: integration-test
        image: integration-test:latest
        build:
            dockerfile: Dockerfile.zscaler
            context: ./src/integration-tests
            additional_contexts:
                util: ./src/shared/code
                certs: ./certs
                game_engine: ./src/game-engine
        environment:
            MQTTBROKER: mqtt-broker
        develop:
            watch:
                - action: sync+restart
                  path: ./src/integration-tests/test.py
                  target: /app/test.py
        restart: no
        networks:
            - pong-network
    gameboard:
        container_name: gameboard
        image: gameboard:latest
        build: ./src/gameboard
        ports:
            - 5000:80
        restart: unless-stopped
        networks:
            - pong-network
networks:
    pong-network:
        name: pong-network
        driver: bridge
