name: Exhibit Deploy

# For production deployment, we will only run when manually triggered,
# taking the branch name as input. The branch should be of the form
# `release/**`, however in the case of a bug sneaking into a release,
# we need to be able to quickly switch to other (presumably hotfix)
# branches, so filtering input is not helpful
#
# TODO: Validate that the supplied branch is a real branch and/or
# provide a list of branches. Partially waiting on GitHub support
# to do this elegantly. Maybe restrict branches in this workflow
# and have a second workflow `deploy-hotfix` that is exactly the
# same without the safeguards for emergencies?

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target Branch'
        required: true
        default: main

# This workflow simply calls `deploy.yml` with production specific arguments
jobs:
  exhibit:
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.inputs.target_branch }}
      app_path: /opt/pong
      server_pub_key: ${{ vars.EXHIBIT_PUBKEY }}
    secrets:
      OVPN_PROFILE: ${{ secrets.OVPN_PROFILE }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_USER: ${{ secrets.EXHIBIT_USER }}
      DEPLOY_HOST: ${{ secrets.EXHIBIT_HOST }}

