name: Container Level Integration Testing

# Testing should be run on every push, no matter the branch
on: push

jobs:
  pytest-game-engine:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/integration-test.yml
    with:
      container-under-test: "game-engine"
      test-container: "game-engine-integration"
      support-containers: "mqtt-broker"

  pytest-human-visualizer:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/integration-test.yml
    with:
      container-under-test: "human-visualizer"
      test-container: "human-visualizer-integration"
      support-containers: "mqtt-broker"

  pytest-ai-paddle-control:
    runs-on: self-hosted
    uses: ./.github/workflows/integration-test.yml
    with:
      container-under-test: "ai-paddle-control-no-gpu"
      test-container: "ai-paddle-control-integration"
      support-containers: "mqtt-broker"