name: Compile Test

# Testing should be run on every push, no matter the branch
on: push

jobs:
  # The most basic of all tests: Does it compile?
  docker-compose-build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Images
        run: docker compose build --parallel
