name: Testing

# Testing should be run on every push, no matter the branch
on: push

jobs:
  # The most basic of all tests: Does it compile?
  docker-compose-build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Images
        run: docker compose build --parallel

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Tests
        working-directory: ${{ github.workspace }}
        run: docker compose -f docker-compose-dev-zscaler-integrationtest.yml up --build -d

      - name: Wait for Container Startup
        run: echo "Waiting for container..." && sleep 120
         
      - name: Check Logs
        run: docker logs integration-test

      - name: Copy Test Results
        run: docker cp integration-test:/app/results.xml ${{ github.workspace }}/results.xml

      - name: Stop Container
        if: always()
        run: docker compose down
          
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: ${{ github.workspace }}/results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: results.xml

     